
" turn off logging to .viminfo
set viminfo=

execute pathogen#infect()

filetype plugin indent on
syntax on

"let g:solarized_termcolors=256
"colorscheme badwolf

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_python_python_exec = 'python3'


syntax enable

set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab

set so=7

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

"filetype indent on

"set mouse=a
"noremap <ScrollWheelUp>      <nop>
"noremap <S-ScrollWheelUp>    <nop>
"noremap <C-ScrollWheelUp>    <nop>
"noremap <ScrollWheelDown>    <nop>
"noremap <S-ScrollWheelDown>  <nop>
"noremap <C-ScrollWheelDown>  <nop>
"noremap <ScrollWheelLeft>    <nop>
"noremap <S-ScrollWheelLeft>  <nop>
"noremap <C-ScrollWheelLeft>  <nop>
"noremap <ScrollWheelRight>   <nop>
"noremap <S-ScrollWheelRight> <nop>
"noremap <C-ScrollWheelRight> <nop>

nnoremap ; :

set virtualedit=onemore
"noremap <silent> <Esc> <C-O>:stopinsert<CR>

" cursor wrap arround
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Be smart when using tabs ;)
"set smarttab

" Linebreak on 500 characters
"set lbr
"set tw=500

"set ai "Auto indent
"set si "Smart indent
"set wrap "Wrap line 

augroup configgroup
    autocmd!
    autocmd VimEnter * highlight clear SignColumn
    autocmd FileType python setlocal commentstring=#\ %s
    autocmd FileType python setlocal shiftwidth=4
    autocmd FileType python setlocal tabstop=4
    autocmd FileType python setlocal softtabstop=4
    autocmd FileType python setlocal expandtab
    autocmd FileType python setlocal number
    autocmd FileType python setlocal showmatch
    autocmd FileType python colorscheme molokai
    autocmd BufEnter *.txt setlocal formatprg=fmt\ -s
    autocmd BufEnter *.txt setlocal spell
    autocmd BufEnter *.txt setlocal spelllang=en_us
    autocmd BufEnter *.txt colorscheme PaperColor
    autocmd BufEnter Makefile setlocal noexpandtab
    autocmd FileType c,cpp,cs,java autocmd BufWritePre <buffer> %s/\s\+$//e
"    autocmd InsertEnter * : silent exec "!printf '\033]50;CursorShape=2\x7'" | exec ":redraw!"
"    autocmd InsertLeave * : silent exec "!printf '\033]50;CursorShape=0\x7'" | exec ":redraw!"
augroup END


